version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install poetry and keyloop dependencies
          command: make install
      - run:
          name: Run Tests
          command: pytest -vvv
  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install poetry
          command: pip install poetry==0.12.17
      - run:
          name: Build and publish to geru-pypi
          command: make publish
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
