version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install poetry and keyloop dependencies
          command: |
            pip install poetry==1.0.5
            poetry config repositories.geru-pypi https://geru-pypi.geru.com.br/simple/
            poetry config http-basic.geru-pypi ${PYPI_USERNAME} ${PYPI_PASSWORD}
            poetry install -vvv
      - run:
          name: Run Tests
          command: |
            poetry run pytest -vvv
  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install poetry
          command: pip install twine poetry==1.0.5
      - run:
          name: Build and publish to geru-pypi
          command: make publish
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
